### ISSUE TITLE
Common licenses as a dropdown list?

### ISSUE THREAD

**Issue by nandana** [oeg-upm/LDP4RO#12]
Can we provide the set of common licenses as a dropdown or do people want to use custom URIs there ? I thought it might be easier if we had a dropdown list for that.

**Comment by dgarijo** [comment]
Nandan already added a dropdown list

**Comment by vroddon** [comment]
Whenever you like I can take a look...
Thanks!!!

Víctor

**Comment by dgarijo** [comment]
Hola Victor,
ahora están puestas a fuego en el código.
Si tienes un servicio que nos diera estas URIs, podrías reabrir el issue y
decirnos como inocarlo?
Gracias,
Dani

2015-04-23 18:11 GMT+02:00 Víctor Rodríguez-Doncel <notifications@github.com

**Comment by nandana** [comment]
@vroddon Yes, it would be nice to talk this with you. Apparently there are two many choices if we put all the licences and not all of them applies to RDF (right?). So I think it would be better to choose a set of most suitable / common ones for Research Objects and put them in the selection.

**Comment by vroddon** [comment]
In practice the choice is limited to a dozen.
I would place in the first place the ODC licenses OpenDataCommons, plus 
an "all rights reserved".
If there is space, also creative commons 4.0

how should be the service? I think we have it...
...is it like "given a string text like 'CC-BY' get me the URI"?

Regards,
Víctor
